<?php
echo '<!DOCTYPE 777>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0"/>';
echo '<title>2nd side of the Triangle</title>';
echo '';
echo '<style>';
echo '*{';
echo 'box-sizing:border-box;';
echo 'font-family:Consolas, monospace;';
echo '}';
echo '';
echo 'body{';
echo 'margin:0;';
echo 'min-height:100vh;';
echo 'background:';
echo 'radial-gradient(circle at top, #111 0%, #050505 45%, #000 100%);';
echo 'color:#d0d0d0;';
echo 'overflow-x:hidden;';
echo '}';
echo '';
echo 'body::before{';
echo 'content:"";';
echo 'position:fixed;';
echo 'inset:0;';
echo 'pointer-events:none;';
echo 'opacity:0.06;';
echo 'background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='180' height='180'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.85'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='1'/%3E%3C/svg%3E");';
echo '}';
echo '';
echo '.container{';
echo 'width:min(900px, 92%);';
echo 'margin:auto;';
echo 'padding:40px 0;';
echo '}';
echo '';
echo 'h1{';
echo 'text-align:center;';
echo 'font-size:3rem;';
echo 'letter-spacing:4px;';
echo 'color:#fff;';
echo 'text-shadow:0 0 12px #444;';
echo 'margin-bottom:10px;';
echo '}';
echo '';
echo '.subtitle{';
echo 'text-align:center;';
echo 'opacity:0.7;';
echo 'margin-bottom:50px;';
echo '}';
echo '';
echo '.quiz{';
echo 'background:rgba(10,10,10,0.92);';
echo 'border:1px solid #1f1f1f;';
echo 'border-radius:18px;';
echo 'padding:22px;';
echo 'margin-bottom:25px;';
echo 'box-shadow:';
echo '0 0 20px rgba(255,255,255,0.03),';
echo 'inset 0 0 25px rgba(255,255,255,0.015);';
echo 'transition:0.3s;';
echo '}';
echo '';
echo '.quiz.correct{';
echo 'border-color:#2c6d2c;';
echo 'box-shadow:';
echo '0 0 25px rgba(0,255,0,0.1),';
echo 'inset 0 0 25px rgba(0,255,0,0.03);';
echo '}';
echo '';
echo '.question-row{';
echo 'display:flex;';
echo 'align-items:center;';
echo 'justify-content:space-between;';
echo 'gap:15px;';
echo 'margin-bottom:18px;';
echo '}';
echo '';
echo '.question{';
echo 'font-size:1.15rem;';
echo 'line-height:1.6;';
echo '}';
echo '';
echo '.speak{';
echo 'background:#151515;';
echo 'border:1px solid #333;';
echo 'color:white;';
echo 'width:50px;';
echo 'height:50px;';
echo 'border-radius:14px;';
echo 'cursor:pointer;';
echo 'font-size:1.3rem;';
echo 'transition:0.25s;';
echo '}';
echo '';
echo '.speak:hover{';
echo 'transform:scale(1.08);';
echo 'background:#222;';
echo '}';
echo '';
echo '.answer-row{';
echo 'display:flex;';
echo 'gap:10px;';
echo '}';
echo '';
echo 'input{';
echo 'flex:1;';
echo 'padding:14px;';
echo 'background:#0c0c0c;';
echo 'border:1px solid #2c2c2c;';
echo 'color:white;';
echo 'border-radius:12px;';
echo 'outline:none;';
echo 'font-size:1rem;';
echo '}';
echo '';
echo 'input:focus{';
echo 'border-color:#666;';
echo 'box-shadow:0 0 10px rgba(255,255,255,0.08);';
echo '}';
echo '';
echo '.submit{';
echo 'padding:14px 20px;';
echo 'border:none;';
echo 'border-radius:12px;';
echo 'background:linear-gradient(to bottom, #222, #111);';
echo 'color:white;';
echo 'cursor:pointer;';
echo 'font-size:1rem;';
echo 'border:1px solid #444;';
echo 'transition:0.25s;';
echo '}';
echo '';
echo '.submit:hover{';
echo 'transform:translateY(-2px);';
echo 'box-shadow:0 0 15px rgba(255,255,255,0.08);';
echo '}';
echo '';
echo '.status{';
echo 'margin-top:12px;';
echo 'font-size:0.95rem;';
echo 'min-height:20px;';
echo '}';
echo '';
echo '.correct-text{';
echo 'color:#7cff7c;';
echo '}';
echo '';
echo '.wrong-text{';
echo 'color:#ff6f6f;';
echo '}';
echo '';
echo '#finalBox{';
echo 'display:none;';
echo 'margin-top:50px;';
echo 'padding:30px;';
echo 'border-radius:20px;';
echo 'background:#070707;';
echo 'border:1px solid #333;';
echo 'text-align:center;';
echo 'animation:fadeIn 1s ease;';
echo '}';
echo '';
echo '#finalText{';
echo 'margin-top:20px;';
echo 'font-size:1.3rem;';
echo 'color:#fff;';
echo 'letter-spacing:2px;';
echo '}';
echo '';
echo '@keyframes fadeIn{';
echo 'from{';
echo 'opacity:0;';
echo 'transform:translateY(25px);';
echo '}';
echo 'to{';
echo 'opacity:1;';
echo 'transform:translateY(0);';
echo '}';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '';
echo '<div class="container">';
echo '';
echo '<h1>2nd side of the Triangle</h1>';
echo '';
echo '<div id="quizContainer"></div>';
echo '';
echo '<div id="finalBox">';
echo '<h2>ALL QUESTIONS SOLVED</h2>';
echo '<div id="finalText">';
echo 'THE FINAL TEXT GOES HERE';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<script>';
echo '/*';
echo '=========================================';
echo 'QUIZ DATA';
echo '=========================================';
echo '*/';
echo 'const quizzes = [';
echo '{';
echo 'name: "What site from Cicada 3301 is an IP, redirected after a site with Prime numbers.",';
echo 'answer: "79.143.189.52"';
echo '},';
echo '{';
echo 'name: "What is the EndScreen of smlwiki.com",';
echo 'answer: "Bouncing Marwin"';
echo '},';
echo '{';
echo 'name: "What do you see when you enter the secret video on the BloodBear game",';
echo 'answer: "Dancing BloodBear"';
echo '},';
echo '{';
echo 'name: "What is the hidden message in the gman jumpscare from the addon 'Anomalies' on the Steam Workshop Author Namericito",';
echo 'answer: "RunConsoleCommand(\"777\")"';
echo '}';
echo '];';
echo '';
echo '/*';
echo '=========================================';
echo 'FINAL TEXT';
echo '=========================================';
echo '*/';
echo 'const finalText = "After all this puzzle, the true one is caged in muzzle, either the danger will be in physical, and maybe in the digital, but the one who is in dark web, will be the one who can answer to all, USE WISELY. http://darkgptqjmtsddq2kthnq7emo6jpxbzxyhn77tutrlinqvovuk7jywid.onion/";';
echo '';
echo '/*';
echo '=========================================';
echo 'VOICE SETTINGS';
echo '=========================================';
echo '*/';
echo 'const voice = "Mike (for Telephone)";';
echo 'const pitch = 113;';
echo 'const speed = 170;';
echo '';
echo 'const container = document.getElementById("quizContainer");';
echo 'let solvedCount = 0;';
echo '';
echo '/*';
echo '=========================================';
echo 'CREATE QUIZZES';
echo '=========================================';
echo '*/';
echo 'quizzes.forEach((quiz, index) => {';
echo '';
echo 'const div = document.createElement("div");';
echo 'div.className = "quiz";';
echo '';
echo 'div.innerHTML = `';
echo '<div class="question-row">';
echo '<div class="question">${quiz.name}</div>';
echo '';
echo '<button class="speak" title="Speak">';
echo '🔊';
echo '</button>';
echo '</div>';
echo '';
echo '<div class="answer-row">';
echo '<input type="text" placeholder="Enter answer..." />';
echo '<button class="submit">Submit</button>';
echo '</div>';
echo '';
echo '<div class="status"></div>';
echo '`;';
echo '';
echo 'const speakBtn = div.querySelector(".speak");';
echo 'const input = div.querySelector("input");';
echo 'const submitBtn = div.querySelector(".submit");';
echo 'const status = div.querySelector(".status");';
echo '';
echo '/*';
echo '=========================================';
echo 'SPEAK BUTTON';
echo '=========================================';
echo '*/';
echo 'speakBtn.onclick = () => {';
echo '';
echo 'const text = encodeURIComponent(quiz.name);';
echo '';
echo 'const api =';
echo '`https://www.tetyys.com/SAPI4/SAPI4?text=${text}` +';
echo '`&voice=${encodeURIComponent(voice)}` +';
echo '`&pitch=${pitch}` +';
echo '`&speed=${speed}`;';
echo '';
echo 'const audio = new Audio(api);';
echo 'audio.play();';
echo '};';
echo '';
echo '/*';
echo '=========================================';
echo 'SUBMIT ANSWER';
echo '=========================================';
echo '*/';
echo 'submitBtn.onclick = () => {';
echo '';
echo 'const userAnswer = input.value.trim();';
echo '';
echo 'if (';
echo 'userAnswer.toLowerCase() ===';
echo 'quiz.answer.toLowerCase()';
echo ') {';
echo '';
echo 'status.innerHTML =';
echo '`<span class="correct-text">Correct. Locked.</span>`;';
echo '';
echo 'div.classList.add("correct");';
echo '';
echo 'input.disabled = true;';
echo 'submitBtn.disabled = true;';
echo 'speakBtn.disabled = true;';
echo '';
echo 'solvedCount++;';
echo '';
echo 'checkAllSolved();';
echo '';
echo '} else {';
echo '';
echo 'status.innerHTML =';
echo '`<span class="wrong-text">Incorrect answer.</span>`;';
echo '}';
echo '};';
echo '';
echo 'container.appendChild(div);';
echo '});';
echo '';
echo '/*';
echo '=========================================';
echo 'CHECK ALL SOLVED';
echo '=========================================';
echo '*/';
echo 'function checkAllSolved(){';
echo '';
echo 'if(solvedCount === quizzes.length){';
echo '';
echo 'document.getElementById("finalBox").style.display = "block";';
echo 'document.getElementById("finalText").textContent = finalText;';
echo '';
echo 'window.scrollTo({';
echo 'top: document.body.scrollHeight,';
echo 'behavior: "smooth"';
echo '});';
echo '}';
echo '}';
echo '</script>';
echo '';
echo '</body>';
echo '</html>';
?>
